
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('MAYARA KALOA DOS SANTOS', 'MAYARA.SANTOS@BENNER.COM.BR', 12, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('TIAGO CUCCO', 'TIAGO.CUCCO@BENNER.COM.BR', 4, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ANDRESSA SCHIESSL', 'ANDRESSA.SCHIESSL@BENNER.COM.BR', 4, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('MIRIANE A. LIMA DA SILVA', 'MIRIANE.SILVA@BENNER.COM.BR', 12, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ANDRÉ DECKER', 'ANDRE.DECKER@BENNER.COM.BR', 10, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('BRUNA LEAL', 'BRUNA.FRANCA@BENNER.COM.BR', 12, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('VANDERLI CARDOSO', 'VANDERLI.CARDOSO@BENNER.COM.BR', 12, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('RAFAELA MONTEBELLER', 'RAFAELA.MONTEBELLER@BENNER.COM.BR', 9, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('SIMONE THEWIS DO ROZARIO', 'SIMONE.ROZARIO@BENNER.COM.BR', 11, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('VANESSA CARVALHO DE JESUS', 'VANESSA.JESUS@BENNER.COM.BR', 2, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('BRUNO DE OLIVEIRA RAFAEL', 'BRUNO.RAFAEL@BENNER.COM.BR', 4, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('MARILZA PEREIRA', 'MARILZAP.2602@GMAIL.COM', 9, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('VANESSA SANTOS', 'VANESSA.SANTOS@BENNER.COM.BR', 11, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('RICARDO DE SOUZA', 'RICARDO.SOUZA@BENNER.COM.BR', 5, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('LEONARDO DE FIGUEIREDO PICKLER', 'LEONARDO.PICKLER@BENNER.COM.BR', 9, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('JOÃO PAULO EFFTING', 'JOAO.EFFTING@BENNER.COM.BR', 5, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('LARISSA SINDY SCHLICHTING', 'LARISSA.SCHLICHTING@BENNER.COM.BR', 10, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('MARIA LUISA F. C. DE FREITAS', 'MARIA.FREITAS@BENNER.COM.BR', 11, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('LUCAS CLEMER BONELLI', 'LUCAS.BONELLI@BENNER.COM.BR', 12, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('JOICE SCHMITZ', 'JOICE.SCHMITZ@BENNER.COM.BR', 12, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('BRUNO AZEVEDO COSTA', 'BRUNO.COSTA@BENNER.COM.BR', 10, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('TIAGO DE OLIVEIRA', 'TIAGO.OLIVEIRA@BENNER.COM.BR', 10, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('THIAGO RODRIGUES', 'THIAGO.R@BENNER.COM.BR', 16, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ISMAEL FERNANDO SCHUBERT', 'ISMAEL.SCHUBERT@BENNER.COM.BR', 2, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ANDERSON LUIS HENCES DA ROSA', 'ANDERSON.ROSA@BENNER.COM.BR', 1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('KELSON ALVES MACIEL JUNIOR', 'KELSON.MACIEL@BENNER.COM.BR', 5, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('THIAGO PEROTTO ZOCOLI', 'THIAGO.ZOCOLI@BENNER.COM.BR', 4, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('IURI AMAURI GIROLOMETO', 'IURI.GIROLOMETO@BENNER.COM.BR', 3, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('JOHN HENRIQUE KLAUMANN', 'JOHN.KLAUMANN@BENNER.COM.BR', 3, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ANGELO LUIZ GRANDE', 'ANGELO.GRANDE@BENNER.COM.BR', 16, 0);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('FERNANDO ALEX', 'FERNANDO.ALEX@BENNER.COM.BR', 14, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('FABIANA RAMOS', 'FABIANA.RAMOS@BENNER.COM.BR', 12, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('DIEGO DUARTE', 'DIEGO.DUARTE@BENNER.COM.BR', 16, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('BRUNO GABRIEL DA SILVA', 'BRUNO.SILVA@BENNER.COM.BR', 16, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ALYSSANDRA LUIZA RUGGIERO', 'ALYSSANDRA.RUGGIERO@BENNER.COM.BR', 1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('GUSTAVO SABEL', 'GUSTAVO.SABEL@BENNER.COM.BR', 10, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('OSVALDO DESCHAMPS NETO', 'OSVALDO.DESCHAMPS@BENNER.COM.BR', 3, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ROBERTO MARTINS DA SILVA', 'ROBERTO.MARTINS@BENNER.COM.BR', 15, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ISABEL SANTOS', 'NENHUM', 17, 0);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('FRANCISCO KRAUTCHUK NETO', 'FRANCISCO.KRAUTCHUK@BENNER.COM.BR', 10, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('CESAR TIETBOHL DE ALBUQUERQUE', 'CESAR.ALBUQUERQUE@BENNER.COM.BR', 8, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ALAN ARLINDO COSTA', 'ALAN.COSTA@BENNER.COM.BR', 11, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ANDRÉ CANDIDO GARCIA', 'ANDRE.GARCIA@BENNER.COM.BR', 11, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('LUIS FELTRIN', 'LUIS.FELTRIN@BENNER.COM.BR', 1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('JULIO CESAR RODRIGUES', 'JULIO.RODRIGUES@BENNER.COM.BR', 12, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('RICARDO CARESIA', 'RICARDO.CARESIA@BENNER.COM.BR', 10, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ISAAC NUNCES BORGES', 'ISAAC.BORGES@BENNER.COM.BR', 10, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('DIEGO SANTOS LUIZ', 'DIEGO.LUIZ@BENNER.COM.BR', 8, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('BRUNO EDUARDO VIEK', 'BRUNO.VIEK@BENNER.COM.BR', 1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('DANIEL ZANELLA', 'DANIEL.ZANELLA@BENNER.COM.BR', 3, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('DOUGLAS VOLLES', 'DOUGLAS.VOLLES@BENNER.COM.BR', 1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('DIRCEU SCHLICKMANN', 'DIRCEU.SCHLICKMANN@BENNER.COM.BR', 1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('RODOLFO SCHMITZ', 'RODOLFO.SCHMITZ@BENNER.COM.BR', 13, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('HENRIQUE MACHADO MUELLER', 'HENRIQUE.MULLER@BENNER.COM.BR', 8, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('RICARDO LUIZ GEBIEN', 'RICARDO.GEBIEN@BENNER.COM.BR', 5, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('JAQUELINE APARECIDA VOITEXEM', 'JAQUELINE.VOITEXEM@BENNER.COM.BR', 11, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ARONILDO MUELLER', 'ARONILDO.MUELLER@BENNER.COM.BR', 1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ANDREIA ADAMI', 'ANDREIA.ADAMI@BENNER.COM.BR', 2, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('WALCIR AUGUSTO WEHRLE', 'WALCIR.WEHRLE@BENNER.COM.BR', 10, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('DANIELA THEWIS MANCHEIN', 'DANIELA.MANCHEIN@BENNER.COM.BR', 2, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('MARCIO FABIO ALTHMANN', 'MARCIO.ALTHMANN@BENNER.COM.BR', 8, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('PAULA LORENA', 'PAULA.LORENA@BENNER.COM.BR', 1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ALEXANDRE DA SILVA', 'ALEXANDRE.SILVA@BENNER.COM.BR', 11, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ROSEMERI KATH', 'ROSEMERI.KATH@BENNER.COM.BR', 15, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('DAIANE SCHWEPE', 'DAIANE.SCHVEPE@BENNER.COM.BR', 5, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('PATRÍCIA SARAIVA', 'PATRICIA.SARAIVA@BENNER.COM.BR', 11, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ALESSANDRO DE SOUZA', 'ALESSANDRO.SOUZA@BENNER.COM.BR', 1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('IVAN MANOEL DA SILVA FILHO', 'IVAN.SILVA@BENNER.COM.BR', 2, 0);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('NÁDIA OCHAKOWSKI RUSSI', 'NADIA.RUSSI@BENNER.COM.BR', 2, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('MATHEUS ADRIANO PEREIRA', 'MATHEUS.PEREIRA@BENNER.COM.BR', 2, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ANNA ORSI', 'ANNA.ORSI@BENNER.COM.BR', 9, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('JONATHAN JASON WILHELMS', 'JONATHAN.WILHELMS@BENNER.COM.BR', 10, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('LUIZ ALBERTO FIAMONCINI GUI', 'LUIZ.GUI@BENNER.COM.BR', 10, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('THIAGO LIPPEL DE ARAUJO', 'THIAGO.ARAUJO@BENNER.COM.BR', 10, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ALEXANDRE FELIX SOUZA', 'ALEXANDRE.SOUZA@BENNER.COM.BR', 10, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('LUANA CEOLIN', 'LUANA.CEOLIN@BENNER.COM.BR', 12, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('THIAGO VINICIUS GAIDZINSKI', 'THIAGO.GAIDZINSKI@BENNER.COM.BR', 5, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ODAIR JOSÉ', 'ODAIR.JOSE@BENNER.COM.BR', 11, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ANA PAULA JUNKES', 'ANA.JUNKES@BENNER.COM.BR', 11, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('APARECIDA CEZERINO', 'APARECIDA.CEZERINO@BENNER.COM.BR', 5, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('AORON BEYER', 'AORON.BEYER@BENNER.COM.BR', 7, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('TATIANA ELOAH PEREIRA', 'TATIANA.PEREIRA@BENNER.COM.BR', 12, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('MARGARETH PAREY VALLI', 'MARGARETH.VALLI@BENNER.COM.BR', 11, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('LILIAN DE OLIVEIRA', 'LILIAN.OLIVEIRA@BENNER.COM.BR', 12, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('JANAINA RIBEIRO LUCIANO', 'JANAINA.RIBEIRO@BENNER.COM.BR', 9, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('FLÁVIO SILVEIRA', 'FLAVIO.SILVEIRA@BENNER.COM.BR', 3, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('CHRISTIAN KLUG', 'CHRISTIAN.KLUG@BENNER.COM.BR', 3, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('MARCO CORNTET', 'MARCO.CORNETET@BENNER.COM.BR', 14, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('DIEGO CUGIKI', 'DIEGO.CUGIKI@BENNER.COM.BR', 10, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('KLEDIR DALÇOQUIO', 'KLEDIR.DALCOQUIO@BENNER.COM.BR', 10, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('LUIZ GUSTAVO PASCHOAL', 'LUIZ.PASCHOAL@BENNER.COM.BR', 4, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('MURILO HUBES BASTOS', 'MURILO.BASTOS@BENNER.COM.BR', 4, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('CLAUDIO SCHWEDER', 'CLAUDIO.SCHWEDER@BENNER.COM.BR', 1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('CHRISTIAN GROSH', 'CHRISTIAN.GROSCH@BENNER.COM.BR', 10, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('BRUNA EMERICH', 'BRUNA.SOUZA@BENNER.COM.BR', 8, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('MARCELO FRAGOSO DOS SANTOS SILVA', 'MARCELO.FRAGOSO@BENNER.COM.BR', 12, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('NICOLA BOGAR UCCIO', 'NICOLA.UCCIO@BENNER.COM.BR', 1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('JUSSARA BONFANTE', 'JUSSARA.BONFANTE@BENNER.COM.BR', 12, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('RAQUEL DENISE EWALD', 'RAQUEL.EWALD@BENNER.COM.BR', 2, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('MARLON MAÇANEIRO JR', 'MARLON.MACANEIRO@BENNER.COM.BR', 7, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ISOLETE PEZZINI', 'ISOLETE.PEZZINI@BENNER.COM.BR', 10, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('RODRIGO BAMBINETI', 'RODRIGO.BAMBINETI@BENNER.COM.BR', 10, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('MICHAEL ALEXANDER PEROSSO', 'MICHAEL.PEROSSO@BENNER.COM.BR', 3, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ALESSANDRO DE SOUZA JÚNIOR', 'ALESSANDRO.VIEIRA@BENNER.COM.BR', 11, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('VALDONEI DOS SANTOS', 'VALDONEI.SANTOS@BENNER.COM.BR', 3, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('VITOR RODRIGO DE OLIVEIRA', 'VITOR.OLIVEIRA@BENNER.COM.BR', 12, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('EDUARDO NEUHAUS', 'EDUARDO.NEUHAUS@BENNER.COM.BR', 10, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ROSE', 'ROSE', 9, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('AMÉRICO IMIANOVSKI JUNIOR', 'AMERICO.IMIANOVSKI@BENNER.COM.BR', 11, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ROBSON GRIPA', 'ROBSON.GRIPA@BENNER.COM.BR', 9, 0);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('MAYARA MOLOSSI', 'MAYARA.MOLOSSI@BENNER.COM.BR', 7, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('RAQUEL SEIBT', 'RAQUEL.SEIBT@BENNER.COM.BR', 2, NULL);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ALEXANDRO CORREA', 'ALEXANDRO.CORREA@BENNER.COM.BR', 1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('BRUNA GARCIA VARGAS', 'BRUNA.VARGAS@BENNER.COM.BR', 2, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('CESAR AUGUSTO SIQUEIRA JUNIOR', 'CESAR.SIQUEIRA@BENNER.COM.BR', 7, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('CLEANDRO GODINHO BOEIRA', 'CLEANDRO.BOEIRA@BENNER.COM.BR', 1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('DANIEL GALINA', 'DANIEL.GALINA@BENNER.COM.BR', 12, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ELIZANDRA VIEIRA GONÇALVES', 'ELIZANDRA.GONCALVES@BENNER.COM.BR', 9, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('FABRICIO FONSECA', 'FABRICIO.FONSECA@BENNER.COM.BR', 10, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('FELIPE JUNIOR MACHADO', 'FELIPE.MACHADO@BENNER.COM.BR', 2, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('FILIPE JACOMOZZI', 'FILIPE.JACOMOZZI@BENNER.COM.BR', 12, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('GUSTAVO DE LEMOS', 'GUSTAVO.LEMOS@BENNER.COM.BR', 2, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('JAN RICARDO KIRSTEN', 'JAN.KIRSTEN@BENNER.COM.BR', 1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('LUCAS OLIVEIRA ROQUE', 'LUCAS.ROQUE@BENNER.COM.BR', 12, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('MAICON WILLIAN BERTIN', 'MAICON.BERTIN@BENNER.COM.BR', 13, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ROBERTO KRIEGER FILHO', 'ROBERTO.FILHO@BENNER.COM.BR', 9, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('TIAGO CRISTIANO GMACH', 'TIAGO.GMACH@BENNER.COM.BR', 5, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('WANDERSON GARCIA LIMA', 'WANDERSON.LIMA@BENNER.COM.BR', 2, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ZENILDA RIBEIRO DE OLIVEIRA', 'RECEPCAO@BENNER.COM.BR', 9, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('PATRICIA SEIBT', 'PATRICIA.SEIBT@BENNER.COM.BR', 1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('TIAGO SANTOS', 'TIAGO.SANTOS@BENNER.COM.BR', 12, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('JAIRO PIERITZ', 'JAIRO@BENNER.COM.BR', 12, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('LEONARDO LUIZ ANTUNES', 'LEONARDO.ANTUNES@BENNER.COM.BR', 12, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('MARLON MENDES', 'MARLON.MENDES@BENNER.COM.BR', 15, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('DEONIZIO HEINZEN', 'DEONIZIO.HEINZEN@BENNER.COM.BR', 2, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('KETLIN CRISTINA BORBA BUSS', 'KETLIN.BUSS@BENNER.COM.BR', 11, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ANA PAULA PRADA', 'ANA.PRADA@BENNER.COM.BR', 10, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('LETÍCIA ELAINE KRAUSS', 'LETICIA.KRAUSS@BENNER.COM.BR', 10, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('AUGUSTO OENING COSTA', 'AUGUSTO.COSTA@BENNER.COM.BR', 5, 0);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('ALEXANDRE CORDEIRO TRAPP', 'ALEXANDRE.TRAPP@BENNER.COM.BR', 16, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('JEAN CARLOS FRANCO', 'JEAN.FRANCO@BENNER.COM.BR', 4, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('DOUGLAS GABRIEL NASCIMENTO', 'DOUGLAS.NASCIMENTO@BENNER.COM.BR', 16, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('NIKSON BARTH', 'NIKSON.BARTH@BENNER.COM.BR', 5, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('WEDERSON RUECKERT', 'WEDERSON.RUECKERT@BENNER.COM.BR', 5, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('LUCIANO FRONZA', 'LUCIANO.FRONZA@BENNER.COM.BR', 5, 0);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Tamiris Fontanella de Lima', 'tamiris.lima@benner.com.br', 1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Thiago Joao Pereira', 'thiago.pereira@benner.com.br',  1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Jefferson Leicht', 'jefferson.leicht@benner.com.br', 1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Allan Longhi Schussler', 'allan.schussler@benner.com.br',  1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Daiane Horn Pageno', 'daiane.pageno@benner.com.br',  1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Rosa Maria Visentainer', 'rosa.visentainer@benner.com.br',  1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Thuane Larissa Sopelsa', 'thuane.sopelsa@benner.com.br', 1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Douglas Alessandro Pagel', 'douglas.pagel@benner.com.br',  1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Daniel Giese Rodrigues', 'daniel.rodrigues@benner.com.br',  1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Andrei Franz Salvador', 'andrei.salvador@benner.com.br',  1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Kleverson Brandalize', 'kleverson.brandalize@benner.com.br',  1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Elias Adriano Silva Ramos', 'elias.ramos@benner.com.br',  1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Jackson Pacher', 'jackson.pacher@benner.com.br',  1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Antonio Carlos Cury', 'antonio.cury@benner.com.br',  1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Jean Carlos Klann', 'jean.klann@benner.com.br',  1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Mauricio Pfleger', 'mauricio.pfleger@benner.com.br',  1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Pandora Jessica Dartibale Tureta', 'pandora.tureta@benner.com.br',  1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Alisson Heinzen de Moraes', 'Alisson.Moraes@benner.com.br',  1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Alessandra Pereira', 'alessandra.pereira@benner.com.br',  1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Josiane França', 'josiane.franca@benner.com.br',  1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Sidney Pereira Dotta', 'sidney.dotta@benner.com.br',  1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Tharlison da Silva Conceicao', 'tharlison.conceicao@benner.com.br',  1, 1);
INSERT INTO clientes ( clientenome, clienteemail, deptoid, clientemktmail) VALUES ('Renan Moritz', 'renan.moritz@benner.com.br',  1, 1);

INSERT INTO DEPARTAMENTOS VALUES ('CORP');
INSERT INTO DEPARTAMENTOS VALUES ('RH');
INSERT INTO DEPARTAMENTOS VALUES ('JUR');
INSERT INTO DEPARTAMENTOS VALUES ('WMS');
INSERT INTO DEPARTAMENTOS VALUES ('LOG');
INSERT INTO DEPARTAMENTOS VALUES ('TMS');
INSERT INTO DEPARTAMENTOS VALUES ('TUR');
INSERT INTO DEPARTAMENTOS VALUES ('TEC');
INSERT INTO DEPARTAMENTOS VALUES ('STAFF');
INSERT INTO DEPARTAMENTOS VALUES ('ESP');
INSERT INTO DEPARTAMENTOS VALUES ('QUA');
INSERT INTO DEPARTAMENTOS VALUES ('SUP');
INSERT INTO DEPARTAMENTOS VALUES ('DOC');
INSERT INTO DEPARTAMENTOS VALUES ('COMERCIAL');
INSERT INTO DEPARTAMENTOS VALUES ('CONSULT');
INSERT INTO DEPARTAMENTOS VALUES ('INFRA');
INSERT INTO DEPARTAMENTOS VALUES ('EXTERNO');


INSERT INTO itenscomprados VALUES (1, 19, '2015-10-04 00:00:00', 8, 1.6900, 13.5200);
INSERT INTO itenscomprados VALUES (1, 22, '2015-10-04 00:00:00', 2, 6.2900, 12.5800);
INSERT INTO itenscomprados VALUES (1, 10, '2015-10-04 00:00:00', 1, 14.9000, 14.9000);
INSERT INTO itenscomprados VALUES (1, 15, '2015-10-05 00:00:00', 6, 3.1900, 19.1400);
INSERT INTO itenscomprados VALUES (1, 16, '2015-10-05 00:00:00', 6, 2.3900, 14.3400);
INSERT INTO itenscomprados VALUES (1, 17, '2015-10-05 00:00:00', 3, 1.6900, 5.0700);
INSERT INTO itenscomprados VALUES (1, 11, '2015-10-05 00:00:00', 6, 1.9900, 11.9400);
INSERT INTO itenscomprados VALUES (1, 12, '2015-10-05 00:00:00', 6, 1.0900, 6.5400);
INSERT INTO itenscomprados VALUES (2, 18, '2015-10-05 00:00:00', 1, 55.9000, 55.9000);
INSERT INTO itenscomprados VALUES (2, 23, '2015-10-05 00:00:00', 1, 16.0000, 16.0000);
INSERT INTO itenscomprados VALUES (7, 27, '2015-10-06 21:52:24', 1, 7.5000, 7.5000);
INSERT INTO itenscomprados VALUES (7, 28, '2015-10-06 21:52:27', 1, 3.6000, 3.6000);
INSERT INTO itenscomprados VALUES (7, 29, '2015-10-06 21:52:54', 1, 2.6500, 2.6500);
INSERT INTO itenscomprados VALUES (7, 30, '2015-10-06 21:53:08', 1, 2.9900, 2.9900);
INSERT INTO itenscomprados VALUES (1, 24, '2015-10-08 22:46:45', 3, 2.7900, 8.3700);
INSERT INTO itenscomprados VALUES (1, 11, '2015-10-08 22:46:58', 3, 2.6900, 8.0700);
INSERT INTO itenscomprados VALUES (1, 13, '2015-10-08 22:47:38', 3, 2.9900, 8.9700);
INSERT INTO itenscomprados VALUES (5, 86, '2015-10-27 00:00:00', 1, 13.0000, 13.0000);
INSERT INTO itenscomprados VALUES (5, 87, '2015-10-27 00:00:00', 1, 9.7000, 9.7000);
INSERT INTO itenscomprados VALUES (5, 88, '2015-10-27 00:00:00', 4, 2.5000, 10.0000);
INSERT INTO itenscomprados VALUES (5, 63, '2015-10-27 00:00:00', 3, 2.7000, 8.1000);
INSERT INTO itenscomprados VALUES (5, 89, '2015-10-27 00:00:00', 1, 2.2000, 2.2000);
INSERT INTO itenscomprados VALUES (5, 91, '2015-10-27 00:00:00', 10, 0.8000, 8.0000);
INSERT INTO itenscomprados VALUES (5, 92, '2015-10-27 00:00:00', 2, 2.4000, 4.8000);
INSERT INTO itenscomprados VALUES (1, 32, '2015-10-08 00:00:00', 1, 5.8900, 5.8900);
INSERT INTO itenscomprados VALUES (1, 9, '2015-10-17 00:00:00', 2, 8.9800, 17.9600);
INSERT INTO itenscomprados VALUES (1, 31, '2015-10-17 00:00:00', 6, 1.7500, 10.5000);
INSERT INTO itenscomprados VALUES (1, 20, '2015-10-17 00:00:00', 1, 16.9800, 16.9800);
INSERT INTO itenscomprados VALUES (11, 30, '2015-10-17 00:00:00', 4, 2.9500, 11.8000);
INSERT INTO itenscomprados VALUES (1, 13, '2015-10-22 00:00:00', 4, 2.9900, 11.9600);
INSERT INTO itenscomprados VALUES (1, 12, '2015-10-22 00:00:00', 10, 1.0900, 10.9000);
INSERT INTO itenscomprados VALUES (1, 11, '2015-10-22 00:00:00', 10, 2.1900, 21.9000);
INSERT INTO itenscomprados VALUES (1, 24, '2015-10-22 00:00:00', 3, 2.7900, 8.3700);
INSERT INTO itenscomprados VALUES (1, 9, '2015-10-24 00:00:00', 1, 8.9800, 8.9800);
INSERT INTO itenscomprados VALUES (1, 30, '2015-10-24 00:00:00', 6, 2.6900, 16.1400);
INSERT INTO itenscomprados VALUES (1, 101, '2015-10-24 00:00:00', 1, 8.0000, 8.0000);
INSERT INTO itenscomprados VALUES (1, 103, '2015-10-24 00:00:00', 1, 12.9000, 12.9000);
INSERT INTO itenscomprados VALUES (1, 105, '2015-10-24 00:00:00', 1, 5.9900, 5.9900);
INSERT INTO itenscomprados VALUES (1, 104, '2015-10-24 00:00:00', 1, 5.9900, 5.9900);
INSERT INTO itenscomprados VALUES (3, 99, '2015-10-15 00:00:00', 5, 4.4600, 22.3000);
INSERT INTO itenscomprados VALUES (2, 96, '2015-10-17 00:00:00', 1, 52.9000, 52.9000);
INSERT INTO itenscomprados VALUES (2, 97, '2015-10-17 00:00:00', 2, 11.5000, 23.0000);
INSERT INTO itenscomprados VALUES (2, 23, '2015-10-17 00:00:00', 1, 14.9000, 14.9000);
INSERT INTO itenscomprados VALUES (2, 98, '2015-10-17 00:00:00', 1, 1.6000, 1.6000);
INSERT INTO itenscomprados VALUES (1, 20, '2015-10-19 00:00:00', 3, 17.9000, 53.7000);
INSERT INTO itenscomprados VALUES (1, 9, '2015-10-27 00:00:00', 1, 8.9800, 8.9800);
INSERT INTO itenscomprados VALUES (1, 62, '2015-10-27 00:00:00', 3, 3.9900, 11.9700);
INSERT INTO itenscomprados VALUES (1, 84, '2015-10-27 00:00:00', 3, 2.9900, 8.9800);
INSERT INTO itenscomprados VALUES (1, 44, '2015-10-27 00:00:00', 6, 1.5900, 9.5400);
INSERT INTO itenscomprados VALUES (1, 21, '2015-10-27 00:00:00', 2, 1.9800, 3.9600);
INSERT INTO itenscomprados VALUES (1, 94, '2015-10-27 00:00:00', 1, 6.9800, 7.6100);
INSERT INTO itenscomprados VALUES (1, 24, '2015-10-21 00:00:00', 3, 2.7900, 8.3700);
INSERT INTO itenscomprados VALUES (1, 21, '2015-10-21 00:00:00', 1, 1.9800, 1.9800);
INSERT INTO itenscomprados VALUES (1, 44, '2015-10-21 00:00:00', 5, 1.7900, 8.9500);
INSERT INTO itenscomprados VALUES (1, 15, '2015-10-05 00:00:00', 1, 3.1900, 3.1900);
INSERT INTO itenscomprados VALUES (7, 27, '2015-10-06 00:00:00', 1, 7.4900, 7.4900);
INSERT INTO itenscomprados VALUES (4, 33, '2015-10-08 00:00:00', 1, 1.4900, 1.4900);
INSERT INTO itenscomprados VALUES (4, 35, '2015-10-08 00:00:00', 1, 14.4800, 14.4800);
INSERT INTO itenscomprados VALUES (4, 9, '2015-10-08 00:00:00', 1, 8.9400, 8.9400);
INSERT INTO itenscomprados VALUES (4, 30, '2015-10-11 00:00:00', 1, 2.6800, 2.6800);
INSERT INTO itenscomprados VALUES (4, 111, '2015-10-11 00:00:00', 1, 8.2800, 8.2800);

DECLARE @prod INT

INSERT INTO produtos VALUES ('PRODUTO TAXA 2.5', NULL, 3, 0, 1, 0);
select @prod = produtoid from produtos where produtonome = 'PRODUTO TAXA 2.5'
INSERT INTO produtosprecovenda VALUES (@prod, '2017-12-05 22:00:00', 2.5);

INSERT INTO produtos VALUES ('PRODUTO TAXA 3', NULL, 3, 0, 1, 0);
select @prod = produtoid from produtos where produtonome = 'PRODUTO TAXA 3'
INSERT INTO produtosprecovenda VALUES (@prod, '2017-12-05 22:00:00', 3);

INSERT INTO produtos VALUES ('PRODUTO TAXA 4', NULL, 3, 0, 1, 0);
select @prod = produtoid from produtos where produtonome = 'PRODUTO TAXA 4'
INSERT INTO produtosprecovenda VALUES (@prod, '2017-12-05 22:00:00', 4);

INSERT INTO produtos VALUES ('PRODUTO TAXA 5', NULL, 3, 0, 1, 0);
select @prod = produtoid from produtos where produtonome = 'PRODUTO TAXA 5'
INSERT INTO produtosprecovenda VALUES (@prod, '2017-12-05 22:00:00', 5);


INSERT INTO unidadesmedida VALUES ('grama', 'g');
INSERT INTO unidadesmedida VALUES ('quilo', 'kg');
INSERT INTO unidadesmedida VALUES ('unidade', 'un');
INSERT INTO unidadesmedida VALUES ('mililitros', 'ml');
INSERT INTO unidadesmedida VALUES ('litros', 'l');


